POST http://localhost:3001/api/blogs
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlbmdhbyIsImlkIjoiNmE1ZTNkNDQ4MDUzYmUyZWIyZTBjZGViIiwiaWF0IjoxNzg1MDU4NDUzfQ.VisEcFZHxuPlnWb-_JrTR6FikN3Xzqi6p9I-lAiKwCI

{
    "title": "CellPhone",
    "author": "Xiaogang Feng",
    "url": "www.cellphone.com",
    "likes": 32456
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json 

{
    "title": "Night Feast",
    "author": "Kaige Chen",
    "url": "www.nightfeast.com",
    "likes": 6547872,
    "userId": "6a5db97e7c4d09cee90e2a7b"
}